name: AngelAchivements
main: com.xangeldlc.Main
version: 1.0
api-version: 1.20
author: xAngelDLC
description: Plugin de logros minecraft.
commands:
  achievementreload:
    description: Recargar la configuración del plugin.
    usage: /<command> reload
